### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by duanestorey** [robertdevore/markdown-exporter-for-wordpress#1]
I just tried installing this on my old WordPress website.  It caused a fatal error when trying to generate the export.

![Screenshot 2024-11-12 at 5 21 35 PM](https://github.com/user-attachments/assets/be9fcf1e-cb10-4da3-b2f8-323da9e0d581)

[13-Nov-2024 01:21:32 UTC] PHP Fatal error:  Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, stdClass given in /home2/xqybismy/public_html/wp-content/plugins/markdown-exporter-for-wordpress/markdown-exporter.php:627
Stack trace:
#0 /home2/xqybismy/public_html/wp-content/plugins/markdown-exporter-for-wordpress/markdown-exporter.php(627): preg_match('/[:\\-{}\\[\\],&*#...', Object(stdClass))
#1 /home2/xqybismy/public_html/wp-content/plugins/markdown-exporter-for-wordpress/markdown-exporter.php(597): Markdown_Exporter->escape_yaml_string(Object(stdClass))
#2 /home2/xqybismy/public_html/wp-content/plugins/markdown-exporter-for-wordpress/markdown-exporter.php(549): Markdown_Exporter->array_to_yaml(Array)
#3 /home2/xqybismy/public_html/wp-content/plugins/markdown-exporter-for-wordpress/markdown-exporter.php(453): Markdown_Exporter->generate_markdown_content(14622)
#4 /home2/xqybismy/public_html/wp-includes/class-wp-hook.php(324): Markdown_Exporter->export_content('')
#5 /home2/xqybismy/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#6 /home2/xqybismy/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /home2/xqybismy/public_html/wp-admin/admin-ajax.php(192): do_action('wp_ajax_markdow...')

**Comment by msurguy** [comment]
Same error on my site.

**Comment by robertdevore** [comment]
Thank you both, I'll be reviewing and pushing out an update later today 🤘

**Comment by robertdevore** [comment]
@duanestorey  @msurguy  can you share the WP version, PHP version and what plugins are active? 

I've tried to replicate the issue on PHP 7.4and 8.3 and both are working for me.

**Comment by duanestorey** [comment]
WordPress 6.7, PHP  8.2.18
Plugins: Akismet, Classic Editor

I took a look at the code.  I think what's happening is some of the post meta data are actually classes, and when they are loaded they are converted into classes directly.  At that point you're trying to turn it into yaml, and I think the code assumes it's an array.  So it's dying.  That's my quick take on it though.

**Comment by duanestorey** [comment]
I did a quick scan of my postmeta table, I have lots of entries like this:

s:52:"a:1:{i:0;O:8:"stdClass":1:{s:3:"tag";s:6:"random";}}";

Looks like an encoded stdClass from some old plugin I likely had active at some point.

**Comment by robertdevore** [comment]
@duanestorey thank you 🙏

I just pushed a commit to the develop branch. Whenever you get a chance, can you try running it to see if it fixes the issue for you?

**Comment by duanestorey** [comment]
2:27:16 UTC] PHP Fatal error:  Uncaught Error: Object of class stdClass could not be converted to string in /home2/xqybismy/public_html/wp-content/plugins/markdown-exporter-for-wordpress/markdown-exporter.php:629
Stack trace:
#0 /home2/xqybismy/public_html/wp-content/plugins/markdown-exporter-for-wordpress/markdown-exporter.php(597): Markdown_Exporter->escape_yaml_string(Object(stdClass))

Seems the same using develop branch

**Comment by duanestorey** [comment]
Added a pull request.

**Comment by robertdevore** [comment]
Merged and will be pushed out with v1.0.1 shortly. Thanks 🙏
